FROM python:3.11-slim

ARG UID=1000
ARG GID=1000
ARG COMMIT_HASH

# Install essential build tools, libraries, and Rust
RUN apt-get update && apt-get install -y --no-install-recommends \
    git \
    build-essential \
    curl \
    lcov \
    && apt-get clean && rm -rf /var/lib/apt/lists/*

# Create a non-root user and prepare directories
RUN groupadd -g $GID regularuser && \
    useradd -m -u $UID -g $GID -s /bin/bash regularuser && \
    mkdir -p /opt && chown -R regularuser /opt

# Switch to non-root user for subsequent steps
USER regularuser

# Install Rust
RUN curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs \
      | sh -s -- --default-toolchain stable -y && \
    echo 'export PATH="$HOME/.cargo/bin:$PATH"' >> ~/.bashrc && \
    echo 'export PATH="$HOME/.cargo/bin:$PATH"' >> ~/.profile && \
    /bin/bash -c "source ~/.cargo/env && rustup update stable"

# Ensure Cargo's bin directory is in PATH
ENV PATH="/home/regularuser/.cargo/bin:${PATH}"

# Create Python virtual environment
RUN python -m venv /opt/venv
ENV PATH="/opt/venv/bin:$PATH"

# Install Python packages into virtual environment
RUN pip install --no-cache-dir \
    coverage==7.6.2 \
    cython \
    unidiff \
    click \
    rich \
    pytest \
    pytest-cov \
    stestr \
    ddt

# Clone the Qiskit repository
WORKDIR /opt
RUN git clone https://github.com/Qiskit/qiskit.git

# Checkout the desired commit hash
WORKDIR /opt/qiskit
RUN git checkout main && git fetch origin && git checkout $COMMIT_HASH

# Install Qiskit in editable mode into virtual environment
RUN python -m pip install --no-cache-dir -U \
    -c constraints.txt \
    -r requirements.txt \
    -r requirements-dev.txt \
    -r requirements-optional.txt \
    -e .

RUN rm -r /opt/qiskit/target/debug

# Setup working directory and adjust permissions
USER root
RUN mkdir -p /workspace && chown -R regularuser /workspace
RUN chown -R regularuser:regularuser /opt && \
    chmod -R regularuser:regularuser /home/regularuser

USER regularuser
WORKDIR /workspace

# Verify installation by printing the Qiskit version
CMD ["/bin/bash", "-c", "du -ah / | sort -rh | head -n 20"]

# command to build the image
# docker build --build-arg UID=$(id -u) --build-arg GID=$(id -g) --build-arg COMMIT_HASH=c4e605ba73006ebaaaf65580c48b8bba72d0949c -t qiskit-base-rust .
# docker run --rm -it -v $(pwd):