FROM python:3.11-slim

ARG UID=1000
ARG GID=1000

# Set up build environment
# For pandas specific build dependencies: see https://github.com/pandas-dev/pandas/blob/main/Dockerfile
RUN apt-get update && apt-get install -y --no-install-recommends \
    git \
    build-essential \
    curl \
    libhdf5-dev \
    libgles2-mesa-dev \
    libglib2.0-0 \
    libsm6 \
    libxrender1 \
    libxext6 \
    && apt-get clean && rm -rf /var/lib/apt/lists/*

# Set environment variables to avoid buffering and locale issues
ENV PYTHONUNBUFFERED=1 LANG=C.UTF-8

# Clone Pandas repository and checkout pull request
WORKDIR /opt
RUN git clone https://github.com/pandas-dev/pandas.git

# Create non-root user and adjust ownership of the Pandas source
RUN groupadd -g $GID regularuser && \
    useradd -m -u $UID -g $GID -s /bin/bash regularuser && \
    chown -R ${UID}:${GID} /opt/pandas

# Setup working directory and adjust permissions
WORKDIR /workspace
RUN chown -R regularuser /workspace

# Switch to non-root user for development/testing purposes.
USER regularuser

# Add the user-local bin directory to PATH so that pip-installed tools (e.g., meson) can be found
ENV PATH="/home/regularuser/.local/bin:$PATH"

WORKDIR /opt/pandas
ARG PR_NUMBER
RUN git config --global alias.pr '!f() { git fetch -fu ${2:-origin} refs/pull/$1/head:pr/$1 && git checkout pr/$1; }; f' \
    && git pr $PR_NUMBER

# Install Pandas dependencies and utilities
RUN pip install --no-cache-dir unidiff click rich && \
    python -m pip install -r requirements-dev.txt

# Install Pandas
# See guide https://pandas.pydata.org/pandas-docs/stable/development/contributing_environment.html
RUN python -m pip install -ve . --no-build-isolation --config-settings editable-verbose=true

WORKDIR /workspace

# RUN pytest -n auto -m "not slow and not network and not db and not single_cpu" --cov=pandas --cov-report=xml /opt/pandas || true
RUN pytest -n auto -m "not slow and not network and not db and not single_cpu" --cov=/opt/pandas --cov-report=xml /opt/pandas || true
# RUN pytest --cov=pandas --cov-report=xml /opt/pandas/pandas/tests/arrays/floating/*
RUN coverage combine ; coverage xml -o /opt/pandas/coverage_all.xml

WORKDIR /workspace
RUN chown -R regularuser /workspace

# Print the version of Pandas
# CMD ["python", "-c", "import pandas as pd; print(pd.__version__)"]
CMD ["/bin/bash", "-c", "du -ah / | sort -rh | head -n 20"]
